#!/bin/bash

# Make sure this file is executable
# chmod +x sniff

if [ `echo "$@" | grep '\-\-fix'` ] || [ `echo "$@" | grep '\-f'` ]; then
    FIX=1
else
    FIX=0
fi

if [ "$FIX" = 1 ]; then
	# Sniff and fix
	vendor/bin/sniff --ignore=vendor/,scripts/,tmp/,logs/,config/Migrations/,webroot/assets/ --extensions=php ./  -v -f
else
	# Sniff only
	vendor/bin/sniff --ignore=vendor/,scripts/,tmp/,logs/,config/Migrations/,webroot/assets/ --extensions=php ./ -v
fi
