<?php

return [
	'Migrations' => ['onlyCli' => true],
	'Shim' => [],
	'Tools' => [],
	'Setup' => [],
	'Data' => [],
	'Ajax' => [],
	//'Meta', ['bootstrap' => false]);
	'Cache' => [],
	'AssetCompress' => [],
	'TinyAuth' => ['bootstrap' => false],
	'Calendar' => [],
	'Search' => [],
	'Ratings' => [],
	'Comments' => [],
	'Geo' => [],
	'Templating' => [],
	'DatabaseLog' => [],
	'Queue' => [],
	'QueueScheduler' => [],
	'Captcha' => [],
	'CakeDto' => [],
	'Cake/Localized' => [],
	'BootstrapUI' => [],
	'Markup' => [],
	'Feedback' => [],
	'Icings/Menu' => [],
	'Expose' => [],
	'Translate' => [],
	'Favorites' => [],
	'QrCode' => [],
	'AuditStash' => [],
	'FileStorage' => [],

	// inside /plugins
	'AuthSandbox' => [],
	'Sandbox' => [],
	'StateMachine' => [],
	'StateMachineSandbox' => [],
];
