<?php

return [
	'Migrations' => ['onlyCli' => true],
	'DebugKit' => ['onlyDebug' => true],
	'TestHelper' => ['onlyDebug' => true, 'optional' => true],
	'CakephpFixtureFactories' => ['onlyDebug' => true, 'onlyCli' => true],
	'Shim' => [],
	'Tools' => [],
	'Setup' => [],
	'Data' => [],
	'Tags' => [],
	'Ajax' => [],
	'Meta' => [],
	'Cache' => [],
	'AssetCompress' => [],
	'TinyAuth' => ['bootstrap' => false],
	'Calendar' => [],
	'Search' => [],
	'Ratings' => [],
	'Comments' => [],
	'Geo' => [],
	'Templating' => [],
	'DatabaseLog' => [],
	'Queue' => [],
	'QueueScheduler' => [],
	'Captcha' => [],
	'CakeDto' => [],
	'Cake/Localized' => [],
	'BootstrapUI' => [],
	'Markup' => [],
	'Feedback' => [],
	'Icings/Menu' => [],
	'Expose' => [],
	'Translate' => [],
	'Favorites' => [],
	'QrCode' => [],
	'AuditStash' => [],
	'FileStorage' => [],
	'Bouncer' => [],
	'Mercure' => [],
	'Workflow' => [],

	// inside /plugins
	'AuthSandbox' => [],
	'Sandbox' => [],
	'WorkflowSandbox' => [],
	'StateMachineSandbox' => [], // Redirects only
];
