<?php

return [
	'Migrations' => [
		'onlyCli' => true,
	],
	'Shim' => [],
	'Tools' => [],
	'Setup' => [],
	'Data' => [],
	'Ajax' => [],
	'Cache' => [],
	'AssetCompress' => [],
	'TinyAuth' => [
		'bootstrap' => false,
	],
	'Calendar' => [],
	'Search' => [],
	'Ratings' => [],
	'Comments' => [],
	'Geo' => [],
	'Templating' => [],
	'DatabaseLog' => [],
	'Queue' => [],
	'Captcha' => [],
	'CakeDto' => [],
	'Cake/Localized' => [],
	'BootstrapUI' => [],
	'Markup' => [],
	'Feedback' => [],
	'Icings/Menu' => [],
	'Expose' => [],
	'Translate' => [],
	'Favorites' => [],
	'QrCode' => [],
	'AuthSandbox' => [],
	'Sandbox' => [],
	'StateMachine' => [],
	'StateMachineSandbox' => [],
	'Crud' => [],
	'CrudDemo' => [],
];
